### ISSUE TITLE
2023.12.24 이슈

### ISSUE THREAD

**Issue by gamrom** [gamrom/gbd#16]
급함 
- [x] 김은식 노종원 두명의 계정의 생일과 이름 변경... 감롬은 생일이 19970801 입니다

안급함
- [x] 어드민이 사용자 이름 수정 가능하게 하는 api

추가개발

**Comment by jomno** [comment]
> 급함
> 
> * [X]  김은식 노종원 두명의 계정의 생일과 이름 변경... 감롬은 생일이 19970801 입니다
> 
> 안급함
> 
> * [ ]  어드민이 사용자 이름 수정 가능하게 하는 api
> 
> 추가개발
