### ISSUE TITLE
24.01.01 이슈

### ISSUE THREAD

**Issue by gamrom** [gamrom/gbd#25]
- [x] 회원 탈퇴 API (파이어베이스에서도 삭제되게)
- [x] 어드민에서 user 정보 받아올때, 성별도 받아올수있게
- [x] 번개 상세 description 줄바꿈처리안됨
- [x] 디스코드 시작시간 종료시간안됨
- [x] 수정시에도 디스코드 알림 가능하게 하고, 디스코드알림보내기
- [x] ogimage제대로 안됨

- [x] 회원가입 시 넣는 날짜가 이상합니다. 회원가입할때 4월 27일 넣으면 27일이 아니라 26일로 저장돼요. 하나씩 뒤로 밀려요 날짜가.. 뭘까요? -> 회원탈퇴 기능만들면 테스트 해봐야할듯합니다

**Comment by jomno** [comment]
- [ ]  회원 탈퇴 API (파이어베이스에서도 삭제되게)
- [X] 어드민에서 user 정보 받아올때, 성별도 받아올수있게
- [ ] 번개 상세 description 줄바꿈처리안됨
[링크](https://velog.io/@choiminwoo2/React%EC%97%90%EC%84%9C-%EC%A4%84%EB%B0%94%EA%BF%88%EC%9D%84-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95) 따라해보쉴?
- [ ] 회원가입 시 넣는 날짜가 이상합니다. 회원가입할때 4월 27일 넣으면 27일이 아니라 26일로 저장돼요. 하나씩 뒤로 밀려요 날짜가.. 뭘까요? -> 회원탈퇴 기능만들면 테스트 해봐야할듯합니다

**Comment by gamrom** [comment]
번개 생성되면, response로 uid만 넘어오는데 번개 생성한사람 이름도 가져올수있게..
