### ISSUE TITLE
24.02.02 

### ISSUE THREAD

**Issue by gamrom** [gamrom/gbd#29]
이슈
- [ ] 벙주를 바꿀 수 없음

추가개발
- [x] 번개를 생성하고 수정 할 때 response 벙주 이름 받기 (현재는 uid만 넘어옴)
- [x] 회원탈퇴 기능

**Comment by jomno** [comment]
- [X] 번개를 생성하고 수정 할 때 response 벙주 이름 받기 (현재는 uid만 넘어옴)
