### ISSUE TITLE
[백엔드] 이슈

### ISSUE THREAD

**Issue by gamrom** [gamrom/gbd#40]
<img width="656" alt="image" src="https://github.com/gamrom/gbd/assets/18091593/8f2b9ebc-56bc-4bf4-8911-b261babb44a4">

<img width="351" alt="image" src="https://github.com/gamrom/gbd/assets/18091593/fcabcf3c-fab3-4375-9a4d-32e8497c6252">

- [x] 위 이미지에 location 으로 하나 더 추가해서 수정부탁드립니다 (안급함)

- [x] patchuser 에 전화번호도 수정가능하게 부탁드립니다 (안급함)

- [x] 로컬에서 데이터 안받아짐 -> 해결
-> 5월에 탄력적 ip 할당이 ec2 과금의 원인인줄알고 삭제했는데, 이게 원인이었고, 로컬 환경변수 변경하니까 정상적으로 데이터 호출.
그런데 문제는...

- [ ] #54
https://us-east-1.console.aws.amazon.com/billing/home#/bills?year=2024&month=5

**Comment by jomno** [comment]
location 추가함

**Comment by jomno** [comment]
patchuser 시 
phone 값으로 변경 가능함
